### ISSUE TITLE
ViewPager Nggak Automate di Page 1

### ISSUE THREAD

**Issue by indrac** [SeptiyanAndika/ViewPager---Swift#10]
Saat di page 1, view pager nya nggak otomatis ke page 2. 
Kalau saya scroll manual ke page 2, baru view pager nya otomatis ke page seterusnya.

Any solution for this Pak?

**Comment by indrac** [comment]
I just know how to fix it by change this line
`viewPager.scrollToPage(0)`

to

`viewPager.scrollToPage(1)`

**Comment by SeptiyanAndika** [comment]
@indrac will check it, thanks for your report

**Comment by indrac** [comment]
No need to do that, already know how to solved it. I wrote it in my above comment.

**Comment by SeptiyanAndika** [comment]
@indrac ah okay thanks, will close this issue.
