### ISSUE TITLE
viewAtIndex index -1

### ISSUE THREAD

**Issue by kamalupasena** [SeptiyanAndika/ViewPager---Swift#4]
I am getting index = -1 in ViewAtIndex

**Comment by SeptiyanAndika** [comment]
Hi @kamalupasena the issue has been fixed in latest commit [56fe2b0](https://github.com/SeptiyanAndika/ViewPager---Swift/commit/56fe2b05cb13d677c8fdf6dab8379bbaca58d73e)

please try again, thanks

**Comment by kamalupasena** [comment]
ok thanx
